import Head from 'next/head'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import Image from 'next/image'

export default function About() {
    return (
        <>
            <Head>
                <title>Travell-In</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/image/logo.png" />
            </Head>
            <Navbar />
            <div className='p-28'>
                <h1 className='text-2xl mb-5'>Tentang Kami</h1>
                <p>
                    Travell-in adalah sebuah website reservasi yang bergerak pada bidang pariwisata pada area Jawa Timur. Reservasi adalah usaha yang dilakukan oleh konsumen untuk memesan jasa atau layanan pada periode waktu tertentu. Reservasi ini berguna untuk memudahkan konsumen saat ingin berkunjung atau datang ke suatu tempat yang hanya perlu melakukan validasi data sesuai dengan yang tertera saat pemesanan.
                </p>
            </div>
            <Footer />
        </>
    )
}