import Head from 'next/head'
import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"
import Image from 'next/image'

export default function Article() {
    const ArticleContent = () => (
        <p className='mb-6'>
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Exercitationem amet officiis hic accusantium, impedit ducimus? Possimus quibusdam eius vitae quidem! Odio corporis illo quo placeat quaerat sunt consequatur consequuntur assumenda!
        </p>
    )
    
    return (
        <>
            <Head>
                <title>Travell-In</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/image/logo.png" />
            </Head>
            <div className="text-[#3D3D3D]">
                <Navbar />
                <div className="text-center mt-20 mb-20">
                    <p>Created on June 24th, 2022</p>
                    <h1 className="text-4xl font-bold">Lorem Ipsum</h1>
                    <p>by Muhammad Rendy Ramadani</p>
                </div>
                <div className="flex justify-center">
                    <Image className='rounded-md border md:w-7/12 w-11/12' src={"/image/Pantai-Klayer.png"} alt={"Pantai Klayer"} width={750} height={400} />
                </div>
                <div className='mx-auto md:w-1/2 w-4/5 mt-10 mb-10'>
                    <h4 className='mb-10 font-bold text-xl'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur asperiores totam nostrum facilis. Nobis ducimus culpa, pariatur dolore veritatis</h4>
                    <ArticleContent/>
                    <ArticleContent/>
                    <ArticleContent/>
                    <ArticleContent/>
                    <ArticleContent/>
                </div>
                <Footer />
            </div>
        </>
    )
}