import Head from 'next/head'
import Image from 'next/image'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

export default function Gallery() {
    return (
        <>
            <Head>
                <title>Travell-In</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/image/logo.png" />
            </Head>
            <Navbar />
            <h1 className='text-[#3D3D3D] font-bold text-2xl text-center m-12'>Gallery Foto Destinasi Wisata</h1>
            <div className='flex md:flex-row flex-col gap-5 md:items-start items-center justify-center md:m-20 mb-10'>
                <div className='flex flex-col gap-5 mt-10'>
                    <div className=''>
                        <Image className='' src={'/image/gallery/1.png'} height={200} width={200} alt={'Gallery'} />
                    </div>
                    <div className=''>
                        <Image src={'/image/gallery/2.png'} height={200} width={200} alt={'Gallery'} />
                    </div>
                    <div className=''>
                        <Image src={'/image/gallery/3.png'} height={200} width={200} alt={'Gallery'} />
                    </div>
                </div>
                <div className='flex flex-col gap-5 mt-5'>
                    <div className=''>
                        <Image src={'/image/gallery/4.png'} height={200} width={200} alt={'Gallery'} />
                    </div>
                    <div className=''>
                        <Image src={'/image/gallery/5.png'} height={200} width={200} alt={'Gallery'} />
                    </div>
                    <div className=''>
                        <Image src={'/image/gallery/6.png'} height={200} width={200} alt={'Gallery'} />
                    </div>
                </div>
                <div className='flex flex-col gap-5'>
                    <div className=''>
                        <Image src={'/image/gallery/7.png'} height={200} width={200} alt={'Gallery'} />
                    </div>
                    <div className=''>
                        <Image src={'/image/gallery/8.png'} height={200} width={200} alt={'Gallery'} />
                    </div>
                    <div className=''>
                        <Image src={'/image/gallery/9.png'} height={200} width={200} alt={'Gallery'} />
                    </div>
                </div>
                <div className='flex flex-col gap-5 mt-10'>
                    <div className=''>
                        <Image src={'/image/gallery/10.png'} height={200} width={200} alt={'Gallery'} />
                    </div>
                    <div className=''>
                        <Image src={'/image/gallery/11.png'} height={200} width={200} alt={'Gallery'} />
                    </div>
                    <div className=''>
                        <Image src={'/image/gallery/12.png'} height={200} width={200} alt={'Gallery'} />
                    </div>
                </div>
            </div>
            <Footer />
        </>
    )
}