import Head from 'next/head'
import Image from 'next/image'
import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"

export default function Home() {
  const CardArticle = () => (
    <div className='text-[#3D3D3D] border shadow rounded-xl'>
      <Image src={'/image/Article.png'} width={160} height={150} className='rounded-xl' alt={'gambar'} />
      <p className='font-medium p-2'>Pantai Klayar</p>
      <p className='w-32 pl-2 pb-2 text-sm'>Lorem ipsum dolor sit amet</p>
    </div>
  )

  return (
    <>
      <Head>
        <title>Travell-In</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/image/logo.png" />
      </Head>
      <main>
        <Navbar />
        <div className='md:flex w-screen'>
          <div className='md:w-3/5 md:pl-14'>
            <div className='text-[#7db9ff] pt-10 p-4'>
              <h1 className='md:text-6xl text-4xl font-bold'>Welcome,
              </h1>
              <h1 className='md:text-7xl text-5xl font-bold tracking-wider'>
                Travell-er!
              </h1>
              <p className='text-[#3D3D3D] md:w-3/5'>Website terbaik untuk menemukan destinasi wisata terbaik di Jawa Timur!</p>
            </div>
            <div>
              <h2 className='text-[#3D3D3D] mt-4 mb-4 font-semibold text-center md:text-start'>Pilih Kategori</h2>
              <div className="grid md:grid-rows-3 grid-rows-4  grid-flow-col gap-2 text-center md:p-0 p-4">
                <div className='border p-6 rounded-md border-[#efdc25] text-[#efdc25] '>
                  <Image className='mx-auto mb-3' src={'/image/Alam.png'} height={30} width={30} alt={'Alam'} />
                  Wisata Alam
                </div>
                <div className='border p-6 rounded-md border-[#ffad82] text-[#ffad82]'>
                  <Image className='mx-auto mb-3' src={'/image/Sejarah.png'} height={30} width={30} alt={'Sejarah'} />
                  Wisata Sejarah
                </div>
                <div className='border p-6 rounded-md border-[#404040] text-[#404040]'>
                  <Image className='mx-auto mb-3' src={'/image/Wahana.png'} height={30} width={30} alt={'Wahana'} />
                  Wisata Wahana
                </div>
                <div className='border p-6 rounded-md border-[#16ad3b] text-[#16ad3b]'>
                  <Image className='mx-auto mb-3' src={'/image/Edukasi.png'} height={30} width={30} alt={'Edukasi'} />
                  Wisata Edukasi
                </div>
                <div className='border p-6 rounded-md border-[#feb9b4] text-[#feb9b4]'>
                  <Image className='mx-auto mb-3' src={'/image/Keluarga.png'} height={30} width={30} alt={'Keluarga'} />
                  Wisata Keluarga
                </div>
                <div className='border p-6 rounded-md border-[#4ebffd] text-[#4ebffd]'>
                  <Image className='mx-auto mb-3' src={'/image/Bahari.png'} height={30} width={30} alt={'Bahari'} />
                  Wisata Bahari
                </div>
                <div className='border p-6 rounded-md border-[#efdc25] text-[#efdc25] md:opacity-0 md:block hidden'>01</div>
                <div className='border p-6 rounded-md border-[#efdc25] text-[#efdc25] md:opacity-0 md:block hidden'>01</div>
                <div className='border p-6 rounded-md border-[#6ffe87] text-[#6ffe87]'>
                  <Image className='mx-auto mb-3' src={'/image/Religi.png'} height={30} width={30} alt={'Religi'} />
                  Wisata Religi
                </div>
              </div>
            </div>
          </div>
          <div className='md:w-1/2 p-5 flex gap-2 justify-center'>
            <div className='flex flex-col gap-2 pt-10'>
              <Image src={'/image/image2.png'} width={200} height={100} className='rounded-xl' alt={'gambar'} />
              <Image src={'/image/image1.png'} width={200} height={100} className='rounded-xl' alt={'gambar'} />
            </div>
            <div className='pt-28'>
              <Image src={'/image/image3.png'} width={215} height={100} className='rounded-xl' alt={'gambar'} />
            </div>
          </div>
        </div>
        <div className='mt-10 mb-10'>
          <h1 className='text-[#3D3D3D] text-center md:text-start font-semibold mb-5 md:pl-20'>Our Best Article</h1>
          <div className='flex gap-4 md:p-0 p-2 justify-center'>
            <CardArticle/>
            <div className='flex gap-3 hidden md:flex'>
            <CardArticle />
            <CardArticle />
            <CardArticle />
            <CardArticle />
            <CardArticle />
            <CardArticle />
            </div>
          </div>
        </div>
        <Footer />
      </main>
    </>
  )
}
