import Head from 'next/head'
import Image from 'next/image'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

export default function Shop() {
    const Card = () => (
        <div className='border w-max p-1 rounded-xl shadow-md snap-center'>
            <Image className='w-full rounded-xl border h-[150px]' width={150} height={100} src={'/image/Baju.png'} alt={''} />
            <h3 className='mb-5 mt-1'>
                CMC Tiga Warna
            </h3>
        </div>
    )
    return (
        <>
            <Head>
                <title>Travell-In</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/image/logo.png" />
            </Head>
            <Navbar />
            <div className='md:p-0 p-4'>
                <div className='border mx-auto md:w-1/2 h-max p-4 relative mb-10 shadow-md mt-10 rounded-xl'>
                    <div className='flex flex-col justify-center items-center'>
                        <input className='border p-2 rounded-md mb-5 w-full' type="text" placeholder='Search a product...' />
                        <button className='p-2 bg-[#7db9ff] text-white rounded-md w-1/2 mt-2 absolute bottom-[-20px]'>Search</button>
                    </div>
                </div>
            </div>
            <div className='text-[#3D3D3D] p-12'>
                <div>
                    <h1 className='font-bold p-4'>Rekomendasi</h1>
                    <div className='overflow-auto snap-x'>
                        <div className='flex w-max gap-5 p-4'>
                            <Card />
                            <Card />
                            <Card />
                            <Card />
                            <Card />
                            <Card />
                            <Card />
                            <Card />
                            <Card />
                        </div>
                    </div>
                </div>
                <div>
                    <h1 className='font-bold p-4'>Produk Terlaris</h1>
                    <div className='overflow-auto snap-x'>
                        <div className='flex w-max gap-5 p-4'>
                            <Card />
                            <Card />
                            <Card />
                            <Card />
                            <Card />
                            <Card />
                            <Card />
                            <Card />
                            <Card />
                        </div>
                    </div>
                </div>
                <div>
                    <h1 className='font-bold p-4'>Harga Promo!</h1>
                    <div className='overflow-auto snap-x'>
                        <div className='flex w-max gap-5 p-4'>
                            <Card />
                            <Card />
                            <Card />
                            <Card />
                            <Card />
                            <Card />
                            <Card />
                            <Card />
                            <Card />
                        </div>
                    </div>
                </div>
            </div>
            <Footer />
        </>
    )
}