import Head from 'next/head'
import Image from 'next/image'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

export default function TourDestination() {
    const Card = () => (
        <div className='flex p-2 border shadow rounded-xl mx-auto mt-4 mb-5'>
            <Image className='rounded-xl' src={'/image/PasarArab.png'} alt={''} width={100} height={100} />
            <div className='pl-4'>
                <h1>Pasar Arab Surabaya</h1>
                <p>Keberagraman Indonesia tercimin di banyaknya suku dan budaya yang dimiliki. Terdapat beberapa kampung di Surabaya yang dibagi berdasarkan etnisnya, salah satunya adalah...</p>
            </div>
        </div>
    )
    return (
        <>
            <Head>
                <title>Travell-In</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/image/logo.png" />
            </Head>
            <Navbar />
            <div className='md:p-0 p-4'>
                <div className='border mx-auto md:w-1/2 h-max p-4 relative mb-10 shadow-md mt-10 rounded-xl'>
                    <div className='flex flex-col justify-center items-center'>
                        <input className='border p-2 rounded-md mb-5 w-full' type="text" placeholder='Search by city...' />
                        <button className='p-2 bg-[#7db9ff] text-white rounded-md w-1/2 mt-2 absolute bottom-[-20px]'>Search</button>
                    </div>
                </div>
            </div>

            <div className='text-[#3D3D3D] md:w-3/5 mx-auto mt-20'>
                <h1 className='font-bold'>Hasil Pencarian Yang Relevan</h1>
                <Card/>
                <Card/>
                <Card/>
                <Card/>
            </div>
            <Footer />
        </>
    )
}